spring:
  datasource:
    url: jdbc:mysql://192.168.0.85:3306/cegz?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: qwert321
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
  data: 
    mongodb:
      custom:
        hosts: 192.168.0.85
        ports: 27017
#        replica-set: mgset-3590061
#        username: root
#        password: root
        database: cegz
        authentication-database: admin
        connections-per-host: 20
        min-connections-per-host: 20
server: 
  url: http://192.168.0.85:8080/
  version: 20180810
  image-url: http://pcgqnlzjb.bkt.clouddn.com/
oss: 
  access-key: b166Tl26Dgw2x0FklVu7CEKg2DMGSwOa6i7fi-_P
  secret-key: xDyKW058j0pLSiK1gkuY0XD8UIxDmJTDlnbFYiSA
  all-bucket: test 
message: 
  url: http://sapi.253.com/msg
  account: ypkj-001
  pwd: Ypkj888888
  status: true
    