spring:
  datasource:
    url: jdbc:mysql://192.168.0.85:3306/cegz?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: qwert321
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
server: 
  url: http://192.168.0.85:8080/
  version: 20180810
  image-url: http://pcgqnlzjb.bkt.clouddn.com/
oss: 
  access-key: b166Tl26Dgw2x0FklVu7CEKg2DMGSwOa6i7fi-_P
  secret-key: xDyKW058j0pLSiK1gkuY0XD8UIxDmJTDlnbFYiSA
  all-bucket: test 
mongo: 
  read:
    user: root
    password: root
    url: 192.168.0.85
    port: 27017
    db: cegz

    